// <auto-generated />
using GymTrackerMobile.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace GymTrackerMobile.Persistence.Migrations;

[DbContext(typeof(GymTrackerDbContext))]
[Migration("20260909120000_AddSwimmingActivityFields")]
partial class AddSwimmingActivityFields
{
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
        modelBuilder.HasAnnotation("ProductVersion", "10.0.0");
    }
}
